name: envpinnslope
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - numpy>=1.22.0
  - scipy>=1.8.0
  - cudatoolkit=11.3
  - pytorch==1.10.1=py3.9_cuda11.3_cudnn8.2.0_0
  - matplotlib
  - ipython
  - jupyter
  - pylops
  - colorcet
  - pip:
    - setuptools_scm
    - torchsummary
    - segyio

